CREATE DATABASE customer_behaviour;

USE customer_behaviour;

select * from customer;

-- what is the total revenue generated by male VS female customers?

select gender, SUM(purchase_amount) as revenue 
from customer
group by gender;

-- Which customer used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'YES' and purchase_amount >= (select AVG(purchase_amount) as average_purchase
						 from customer
                         );
                         
-- Which are the top 5 products with highest average review rating

select item_purchased, ROUND(AVG(review_rating), 1) as average_review
from customer
group by item_purchased
order by average_review desc
limit 5;

-- compare the average purchase amounts between standard and express shipping

select shipping_type, AVG(purchase_amount) as average_purchase_amount
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

-- Do subscribed customers spend more? compare average spend and total revenue between subscriber and non subscriber

select subscription_status,
COUNT(customer_id) as total_customers, 
AVG(purchase_amount) as average_spent, 
SUM(purchase_amount) as revenue
from customer
group by subscription_status
order by revenue, average_spent desc;

-- which 5 products have the higest percentage of purchases with discount applied

select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100, 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each purchases

with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END as customer_segment
from customer)

select customer_segment, COUNT(*) as "number of customer"
from customer_type
group by customer_segment;
    
-- what are top 3 most purchased products within each category

select SUM(previous_purchases), item_purchased, category
from customer
group by category, item_purchased;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group;

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;










